robot:
  # Publish all joint states -----------------------------------
  joint_state_controller_gazebo:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  base_controller_gazebo:
    type: effort_controllers/JointPositionController
    joint: ArmYRotCont
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_controller_gazebo:
    type: effort_controllers/JointPositionController
    joint: ArmRot1Rev
    pid: {p: 19000.0, i: 50, d: 100}
  elbow_controller_gazebo:
    type: effort_controllers/JointPositionController
    joint: ArmRot2Rev
    pid: {p: 19000.0, i: 50, d: 100}
